const state={selectedProduct:null,paymentId:null,checkTimer:null,customer:null};
const money=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const activeBooks=()=>LIVROS.filter(b=>b.ativo);
function renderHeroCovers(){const c=document.getElementById("heroCovers"),books=activeBooks().slice(0,3);c.innerHTML=books.map((b,i)=>`<img src="${b.capa}" alt="${b.titulo}" class="rounded-2xl w-full h-44 sm:h-64 object-cover shadow ${i===1?'-translate-y-4':''}">`).join("");document.getElementById("heroComboPrice").textContent=money(COMBO.preco)}
function renderBooks(list=activeBooks()){const g=document.getElementById("booksGrid");if(!list.length){g.innerHTML=`<p class="col-span-3 text-center text-gray-600">Nenhum livro encontrado.</p>`;return}g.innerHTML=list.map(b=>`<article class="bg-white rounded-3xl shadow-md overflow-hidden hover:shadow-xl transition border border-amber-100 flex flex-col"><div class="bg-orange-100 p-4"><img src="${b.capa}" alt="${b.titulo}" class="w-full h-72 object-cover rounded-2xl shadow"></div><div class="p-6 flex flex-col flex-1"><div class="flex items-center justify-between gap-2 mb-3"><span class="bg-amber-100 text-amber-800 text-xs font-black px-3 py-1 rounded-full">${b.categoria}</span><span class="text-xs text-gray-500">${b.paginas} páginas</span></div><h3 class="text-xl font-black text-amber-950 leading-tight">${b.titulo}</h3><p class="font-bold text-orange-600 text-sm mt-1">${b.subtitulo}</p><p class="text-gray-600 mt-3 text-sm leading-relaxed flex-1">${b.descricao}</p><div class="mt-5"><div class="text-3xl font-black text-amber-950">${money(b.preco)}</div><p class="text-xs text-gray-500">PDF para baixar e imprimir</p></div><button data-buy="${b.id}" class="buy-btn block w-full text-center mt-5 bg-orange-500 hover:bg-orange-600 text-white font-extrabold py-3 px-4 rounded-xl shadow transition">Comprar este livro via Pix</button></div></article>`).join("")}
function renderCombo(){const books=activeBooks(),sep=books.reduce((s,b)=>s+b.preco,0),sav=sep-COMBO.preco;document.getElementById("separatePrice").textContent=money(sep);document.getElementById("comboPrice").textContent=money(COMBO.preco);document.getElementById("comboSavings").textContent=sav>0?`Economia de ${money(sav)}`:"";document.getElementById("comboTitle").textContent=`Leve os ${books.length} livros por um preço especial.`;document.getElementById("comboDescription").textContent=COMBO.descricao;document.getElementById("comboList").innerHTML=books.map(b=>`<li>✔ ${b.titulo} — ${b.subtitulo}</li>`).join("")+`<li>✔ Arquivos em PDF</li><li>✔ Download imediato após aprovação do Pix</li><li>✔ Impressão ilimitada para uso pessoal/educativo</li>`}
function setupSearch(){document.getElementById("searchInput").addEventListener("input",e=>{const t=e.target.value.trim().toLowerCase();renderBooks(activeBooks().filter(b=>b.titulo.toLowerCase().includes(t)||b.subtitulo.toLowerCase().includes(t)||b.descricao.toLowerCase().includes(t)||b.categoria.toLowerCase().includes(t)))})}
function findProduct(id){if(id==="combo")return{id:COMBO.id,titulo:COMBO.titulo,descricao:COMBO.subtitulo,preco:COMBO.preco,tipo:"combo",itens:activeBooks().map(b=>b.id)};const b=activeBooks().find(x=>x.id===id);return b?{id:b.id,titulo:b.titulo,descricao:b.subtitulo,preco:b.preco,tipo:"livro",itens:[b.id]}:null}
function setupBuyButtons(){document.body.addEventListener("click",e=>{const btn=e.target.closest("[data-buy]");if(!btn)return;const p=findProduct(btn.getAttribute("data-buy"));if(!p)return alert("Produto não encontrado ou inativo.");openCheckout(p)})}
function openCheckout(p){state.selectedProduct=p;state.paymentId=null;clearInterval(state.checkTimer);document.getElementById("checkoutModal").classList.remove("hidden");document.getElementById("modalTitle").textContent=p.titulo;document.getElementById("modalSubtitle").textContent=`${money(p.preco)} • Pagamento via Pix`;renderCustomerForm(p)}
function renderCustomerForm(p){document.getElementById("checkoutContent").innerHTML=`<form id="customerForm" class="space-y-4"><div class="bg-amber-50 border border-amber-100 rounded-2xl p-4"><p class="font-black text-amber-950">${p.titulo}</p><p class="text-sm text-gray-600">${p.descricao||""}</p><p class="text-2xl font-black text-orange-500 mt-2">${money(p.preco)}</p></div><div><label class="block text-sm font-bold text-gray-700 mb-1">Seu nome</label><input id="customerName" required type="text" placeholder="Digite seu nome" class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-4 focus:ring-orange-200"></div><div><label class="block text-sm font-bold text-gray-700 mb-1">Seu e-mail</label><input id="customerEmail" required type="email" placeholder="seuemail@exemplo.com" class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-4 focus:ring-orange-200"><p class="text-xs text-gray-500 mt-1">Use um e-mail real para identificação do pagamento.</p></div><button type="submit" class="w-full bg-green-500 hover:bg-green-600 text-white font-black px-6 py-4 rounded-2xl shadow">Gerar Pix</button></form>`;document.getElementById("customerForm").addEventListener("submit",e=>{e.preventDefault();state.customer={name:document.getElementById("customerName").value.trim(),email:document.getElementById("customerEmail").value.trim()};document.getElementById("checkoutContent").innerHTML=`<div class="text-center"><div class="loader mx-auto"></div><p class="mt-4 text-gray-600">Gerando Pix...</p></div>`;createPix(p)})}
function closeCheckout(){document.getElementById("checkoutModal").classList.add("hidden");clearInterval(state.checkTimer)}
function setupModalClose(){document.body.addEventListener("click",e=>{if(e.target.matches("[data-close-modal]"))closeCheckout()})}
async function createPix(p){try{const r=await fetch("/.netlify/functions/criar-pix",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...p,customer:state.customer})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erro ao gerar Pix.");state.paymentId=d.paymentId;renderPix(d);startPaymentCheck(p,d.paymentId)}catch(err){document.getElementById("checkoutContent").innerHTML=`<div class="bg-red-50 border border-red-200 text-red-700 p-4 rounded-2xl"><strong>Erro ao gerar Pix.</strong><p class="mt-2 text-sm">${err.message}</p><p class="mt-2 text-xs">Confira se a variável MP_ACCESS_TOKEN foi configurada no Netlify.</p></div>`}}
function renderPix(d){document.getElementById("checkoutContent").innerHTML=`<div class="text-center"><p class="font-bold text-amber-950">Escaneie o QR Code ou copie o código Pix</p>${d.qrCodeBase64?`<img class="qr-img mt-4" src="data:image/png;base64,${d.qrCodeBase64}" alt="QR Code Pix">`:""}<div class="mt-5 bg-amber-50 border border-amber-100 rounded-2xl p-4 text-left"><p class="text-xs font-bold text-gray-500 mb-2">Pix copia e cola:</p><p id="pixCode" class="copy-field text-xs text-gray-700">${d.qrCode||""}</p></div><button id="copyPixBtn" class="mt-4 bg-orange-500 hover:bg-orange-600 text-white font-black px-5 py-3 rounded-xl">Copiar código Pix</button><p class="mt-4 text-sm text-gray-600">Após pagar, aguarde. O download será liberado automaticamente.</p><div class="mt-4 text-xs text-gray-500">Status: aguardando pagamento...</div></div>`;document.getElementById("copyPixBtn").addEventListener("click",async()=>{await navigator.clipboard.writeText(d.qrCode||"");document.getElementById("copyPixBtn").textContent="Código copiado!"})}
function startPaymentCheck(p,id){state.checkTimer=setInterval(async()=>{try{const r=await fetch(`/.netlify/functions/verificar-pagamento?paymentId=${encodeURIComponent(id)}`);const d=await r.json();if(d.status==="approved"){clearInterval(state.checkTimer);showDownload(p,id)}}catch(e){console.error(e)}},5000)}
function showDownload(p,id){const url=`/.netlify/functions/download?paymentId=${encodeURIComponent(id)}&productId=${encodeURIComponent(p.id)}`;document.getElementById("checkoutContent").innerHTML=`<div class="text-center"><div class="text-6xl">✅</div><h3 class="mt-4 text-2xl font-black text-amber-950">Pagamento aprovado!</h3><p class="mt-2 text-gray-600">Seu material já está liberado.</p><a href="${url}" class="inline-block mt-6 bg-green-500 hover:bg-green-600 text-white font-black px-8 py-4 rounded-2xl shadow">Baixar agora</a><p class="mt-4 text-xs text-gray-500">Guarde seu arquivo em local seguro após o download.</p></div>`}
document.addEventListener("DOMContentLoaded",()=>{renderHeroCovers();renderBooks();renderCombo();setupSearch();setupBuyButtons();setupModalClose()});
